# Cache Dir media spec
urn = "media:cache-dir;textable"
media_type = "text/plain"
title = "Cache Dir"
profile_uri = "https://capdag.com/schema/cache_dir"
description = "Cache Dir value"

[validation]
pattern = "^[^\\0]+$"