# Frontmatter Text media spec
urn = "media:frontmatter;textable"
media_type = "text/plain"
title = "Frontmatter Text"
profile_uri = "https://capdag.com/schema/frontmatter_text"
description = "Frontmatter Text text input"

[validation]
max_length = 131072
min_length = 50