# Index Range media spec
urn = "media:index-range;textable"
media_type = "text/plain"
title = "Index Range"
profile_uri = "https://capdag.com/schema/index_range"
description = "Index Range value"

[validation]
pattern = "^\\d+(-\\d*)?$"