# Max Context Length media spec
urn = "media:max-context-length;textable;numeric"
media_type = "text/plain"
title = "Max Context Length"
profile_uri = "https://capdag.com/schema/max_context_length"
description = "Max Context Length numeric value"

[validation]
max = 131072
min = 512